language: c

branches:
  only:
  - master

before_script:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh assertthat
  - ./travis-tool.sh github_package jimhester/covr

script: ./travis-tool.sh run_tests

after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
